### ISSUE TITLE
URL option for installer

### ISSUE THREAD

**Issue by brooke-ec** [ghostdevv/cc-carl#8]
It would significantly improve the development experience if there was an option to specify the branch or URL to install carl from when using the installer. Obviously this would also require some changes to the repository definition, so I'm not sure of the best way to achieve this.

**Comment by ghostdevv** [comment]
Based on #11 I'm not sure I follow what you mean

**Comment by brooke-ec** [comment]
This issue requests the ability to install carl from alternative repositories, using a cli option on the installer. For example, `wget run https://carl.willow.sh/install installer-url` would install carl from the `installer-url` branch.

**Comment by brooke-ec** [comment]
https://github.com/ghostdevv/cc-carl/pull/11#issuecomment-1975156022
> It would be better to achieve this using some kind of development mode that runs a server locally and hosts a modified install script. This could also allow you to test unpushed local changes which would be significantly better!
